# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, help_text='Birthday', null=True)),
                ('qq', models.BigIntegerField(blank=True, default=0, help_text='QQ', null=True)),
                ('remark', models.CharField(blank=True, default='', help_text='Remark', max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, default='', help_text='Mobile', max_length=32, null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone', max_length=32, null=True)),
                ('address', models.CharField(blank=True, default='', help_text='Address', max_length=512, null=True)),
            ],
        ),
    ]
