# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 07:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techuuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^[\\d]{10,14}$', '\u65e0\u6548\u7684\u624b\u673a\u53f7\u7801')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='techuuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^[\\d-]+$', '\u65e0\u6548\u7684\u7535\u8bdd\u53f7\u7801')], verbose_name='Phone'),
        ),
    ]
