# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_info', '0001_initial'),
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EduProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'School Admin'), (2, 'Teacher'), (3, 'Student'), (4, 'Parent')], verbose_name='Role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='edu_info.School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='edu_info.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='techuuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='auth_user.DatabaseFile/data/filename/mimetype'),
        ),
        migrations.AddField(
            model_name='techuuser',
            name='edu_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth_user.EduProfile'),
        ),
    ]
