# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 03:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_auto_20160506_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techuuser',
            name='edu_profile',
        ),
        migrations.AddField(
            model_name='eduprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
