# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 07:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_auto_20160412_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='techuuser',
            name='context',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
