# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_techuuser_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='techuuser',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Gender'),
        ),
    ]
