# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 06:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_auto_20160511_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techuuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^1[\\d]{10}$', '\u65e0\u6548\u7684\u624b\u673a\u53f7\u7801')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='techuuser',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'techu'), (1, 'xplatform'), (2, 'once_xplatform'), (3, 'hejiaoyu'), (4, 'pangu')], default=0, verbose_name='User Source'),
        ),
    ]
