# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 07:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_auto_20160621_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techuuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^1[\\d]{10}$', 'Invalid mobile number.')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='techuuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^[\\d-]+$', 'Invalid phone number.')], verbose_name='Phone'),
        ),
    ]
