# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_auto_20160420_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='techuuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nickname'),
        ),
    ]
