# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_techuuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprofile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'School Admin'), (2, 'Teacher'), (3, 'Student'), (4, 'Parent')], default=0, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='eduprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='edu_info.School'),
        ),
        migrations.AlterField(
            model_name='eduprofile',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='edu_info.Subject'),
        ),
    ]
