# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_auto_20160425_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='techuuser',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'techu'), (1, 'xplatform')], default=0, verbose_name='User Source'),
        ),
    ]
