# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_techuuser_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techuuser',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'techu'), (1, 'xplatform'), (2, 'once_xplatform')], default=0, verbose_name='User Source'),
        ),
    ]
