# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_info', '0002_auto_20160425_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='pinyin',
            field=models.CharField(default='', max_length=255, verbose_name='Scool PinYin'),
        ),
    ]
