# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_info', '0003_school_pinyin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='School ID'),
        ),
    ]
