# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_info', '0006_school_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set([('name', 'category', 'area_code')]),
        ),
    ]
