rproxy:
    extends:
        file: common.yml
        service: web_proxy
    ports:
     - "5000:8000"
     - "5001:8001"
    volumes:
     - ./rproxy/nginx/nginx.conf:/opt/openresty/nginx/conf/nginx.conf:ro
    volumes_from:
     - web:ro
    links:
     - web:web
     - db_proxy:db_proxy
     - cache:cache

web:
    extends:
        file: common.yml
        service: web
    volumes:
     - ./auth_apps/auth_apps:/code
     - /code/static
    links:
     - db_proxy:db_proxy
     - cache:cache
     - celery_redis:redis
    command: ./run-site.sh 

celery_worker:
    extends:
        file: common.yml
        service: web
    volumes:
     - ./auth_apps/auth_apps:/code
    links:
     - db_proxy:db_proxy
     - cache:cache
     - celery_redis:redis
    command: ./run-task-worker.sh

celery_redis:
    image: "docker.zuoyetong.com.cn:8888/redis:3"
    log_opt:
        max-size: "5m"
        max-file: "1"

cache:
    image: "docker.zuoyetong.com.cn:8888/memcached:1.4"
    log_opt:
        max-size: "5m"
        max-file: "1"

db_proxy:
    extends:
        file: common.yml
        service: db_proxy
    
db:
    extends:
        file: common.yml
        service: db
    volumes:
     - ./db/pgdata:/var/lib/postgresql/data
    net: "container:db_proxy"
