rproxy:
    image: "nginx:1.9"
    ports:
     - "5000:5000"
    volumes:
     - ./rproxy/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./rproxy/sslkey:/etc/nginx/sslkey:ro
     - ./static:/var/www/static:ro 
    links:
     - web:web

web:
    image: "auth_apps:latest"
    volumes:
     - ./static:/code/static
    environment:
     - DJANGO_DEBUG=1
     - DJANGO_HOST=auth-center.domain.com.cn
     - EMAIL_USE_SSL=1
     - EMAIL_USE_TLS=0
     - EMAIL_HOST=stmp.163.com
     - EMAIL_HOST_USER=<your email account>
     - EMAIL_HOST_PASSWORD=<your email password>
     - EMAIL_PORT=994
    links:
     - db:db
     - cache:cache
    command: ./run-site.sh 

cache:
    image: "memcached:1.4"

db:
    image: "mysql:5.6"
    volumes:
     - ./db/data:/var/lib/mysql
    environment:
     - MYSQL_USER=mysql
     - MYSQL_PASSWORD=auth_center123
     - MYSQL_ROOT_PASSWORD=auth_center123
     - MYSQL_DATABASE=auth_center
