rproxy:
    image: "docker.zuoyetong.com.cn:8888/nginx:1.9"
    ports:
     - "5000:443"
    volumes:
     - ./rproxy/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./rproxy/sslkey:/etc/nginx/sslkey:ro
    volumes_from:
     - web:ro
    links:
     - web:web

web:
    image: "docker.zuoyetong.com.cn:8888/account_web:latest"
    volumes:
     - /code/static
    environment:
     - DJANGO_DEBUG=1
     - DJANGO_HOST=auth-center.domain.com.cn
     - EMAIL_USE_SSL=1
     - EMAIL_USE_TLS=0
     - EMAIL_HOST=stmp.163.com
     - EMAIL_HOST_USER=<your email account>
     - EMAIL_HOST_PASSWORD=<your email password>
     - EMAIL_PORT=994
     - MEMCACHED_ADDR=cache
     - MEMCACHED_PORT=11211
     - SMS_SERVICE_URL=http://test.com
    links:
     - db:db
     - cache:cache
    command: ./run-site.sh 

cache:
    image: "docker.zuoyetong.com.cn:8888/memcached:1.4"

db:
    image: "docker.zuoyetong.com.cn:8888/mysql:5.6"
    volumes:
     - ./db/data:/var/lib/mysql
    environment:
     - MYSQL_USER=mysql
     - MYSQL_PASSWORD=account_center123
     - MYSQL_ROOT_PASSWORD=account_center123
     - MYSQL_DATABASE=account_center
